### ISSUE TITLE
Division operator is not working properly.

### ISSUE THREAD

**Issue by sabikrahat** [algoramming/ewu_job_portal#3]
Have tried in the canvas ১২ ÷ ২ । It Shows me ১২ - ৯৯২ : -৯৮০

![image](https://user-images.githubusercontent.com/49031412/202166665-af33c06f-776b-4f38-bfaf-0acd49e0e18f.png)

![image](https://user-images.githubusercontent.com/49031412/202166740-e5df287e-c036-4fee-94e5-3df692b05c67.png)

**Comment by algoramming** [comment]
There is an issue in detecting `[÷]` operator. The individual 3 part of that `[÷] `operator detect individually. For that reason we have change the division operator from `[÷]` to `[/]` sign. You can try with this action.

`Moreover, I'm still working on it to detect division sign of that [÷] view.`

![image](https://user-images.githubusercontent.com/81485175/202167128-428be709-3737-4b5c-a9fc-c14ba79d27c5.png)
